### ISSUE TITLE
unable to solve module 'config/firebase'

### ISSUE THREAD

**Issue by jacky0905** [zeckdude/react-native-expo-firebase-chat#1]
could you add config folder too?
how can I run your project?

**Comment by zeckdude** [comment]
Hi @jacky0905,

Sorry for the late reply. I have actually refactored a bunch of code, so make sure to pull the latest from `master` and then add the `config/firebase.js` file with the following content (make sure to fill in the values from your own firebase account):

```js
export default {
  API_KEY: <API_KEY>,
  AUTH_DOMAIN: <AUTH_DOMAIN>,
  DATABASE_URL: <DATABASE_URL>,
  PROJECT_ID: <PROJECT_ID>,
  STORAGE_BUCKET: <STORAGE_BUCKET>,
  MESSAGING_SENDER_ID: <MESSAGING_SENDER_ID>,
};
```

You can see that being used in `lib/firebase.js`

**Comment by zeckdude** [comment]
@jacky0905 Let me know if you need any more help.

**Comment by zeckdude** [comment]
Since I haven't heard anything about this issue, I'm going to close it. If you need any more help, just reply.
